	EXTRN   _float_negate:PROC
	EXTRN   _float_add:PROC
	EXTRN   _float_subtract:PROC
	EXTRN   _float_multiply:PROC
	EXTRN   _float_divide:PROC
	EXTRN   _float_compare:PROC
	EXTRN   _float_convert:PROC

	EXTRN   _write_integer:PROC
	EXTRN   _write_real:PROC
	EXTRN   _write_boolean:PROC
	EXTRN   _write_char:PROC
	EXTRN   _write_string:PROC
	EXTRN   _write_line:PROC

	EXTRN   _read_integer:PROC
	EXTRN   _read_real:PROC
	EXTRN   _read_char:PROC
	EXTRN   _read_line:PROC

	EXTRN   _std_end_of_file:PROC
	EXTRN   _std_end_of_line:PROC

	EXTRN   _std_abs:PROC

	EXTRN   _std_arctan:PROC
	EXTRN   _std_cos:PROC
	EXTRN   _std_exp:PROC
	EXTRN   _std_ln:PROC
	EXTRN   _std_sin:PROC
	EXTRN   _std_sqrt:PROC

	EXTRN   _std_round:PROC
	EXTRN   _std_trunc:PROC
