	EXTRN   _FloatNegate:PROC
	EXTRN   _FloatAdd:PROC
	EXTRN   _FloatSubtract:PROC
	EXTRN   _FloatMultiply:PROC
	EXTRN   _FloatDivide:PROC
	EXTRN   _FloatCompare:PROC
	EXTRN   _FloatConvert:PROC

	EXTRN   _WriteInteger:PROC
	EXTRN   _WriteReal:PROC
	EXTRN   _WriteBoolean:PROC
	EXTRN   _WriteChar:PROC
	EXTRN   _WriteString:PROC
	EXTRN   _WriteLine:PROC

	EXTRN   _ReadInteger:PROC
	EXTRN   _ReadReal:PROC
	EXTRN   _ReadChar:PROC
	EXTRN   _ReadLine:PROC

	EXTRN   _StdEof:PROC
	EXTRN   _StdEoln:PROC

	EXTRN   _StdAbs:PROC

	EXTRN   _StdArctan:PROC
	EXTRN   _StdCos:PROC
	EXTRN   _StdExp:PROC
	EXTRN   _StdLn:PROC
	EXTRN   _StdSin:PROC
	EXTRN   _StdSqrt:PROC

	EXTRN   _StdRound:PROC
	EXTRN   _StdTrunc:PROC
