//fig 2-9
//  *************************************************************
//  *                                                           *
//  *   M I S C E L L A N E O U S   (Header)                    *
//  *                                                           *
//  *   FILE:    prog2-1/misc.h                                 *
//  *                                                           *
//  *   MODULE:  Common                                         *
//  *                                                           *
//  *   Copyright (c) 1996 by Ronald Mak                        *
//  *   For instructional purposes only.  No warranties.        *
//  *                                                           *
//  *************************************************************

#ifndef misc_h
#define misc_h

const int false = 0;
const int true  = 1;

#endif
//endfig
